### ISSUE TITLE
Investigate issue with mouse metadata

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#303]
```
[2024-02-26 15:04:12,926] ERROR in schema_manager: Invalid expression (string value): {'bedding': '1/4-inch corncob', 'cage_enhancements': 'Nestlets', 'date_of_birth_or_fertilization': '10.08.2019', 'date_of_death': '02.08.2022', 'diet': 'NIH-31 Diet', 'euthanization_method': 'Inhaled anesthetic agents', 'is_deceased': 'TRUE', 'is_embryo': 'FALSE', 'light_cycle': 'Standard/default', 'local_lifespan_data': '', 'rack_setup': 'Ventilated', 'room_health_status': 'Other', 'room_temperature': '23', 'sex': 'M', 'strain': '
C57BL/6J', 'strain_rrid': 'IMSR_JAX:000664', 'water_source': 'RO Water'} to be evaluated by ast.literal_eval()
Traceback (most recent call last):
  File "/usr/src/app/src/./schema/schema_manager.py", line 1921, in convert_str_to_data
    data = ast.literal_eval(data_str)
  File "/usr/lib64/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {'bedding': '1/4-inch corncob', 'cage_enhancements': 'Nestlets', 'date_of_birth_or_fertilization': '10.08.2019', 'date_of_death': '02.08.2022', 'diet': 'NIH-31 Diet', 'euthanization_method': 'Inhaled anesthetic agents', 'is_deceased': 'TRUE', 'is_embryo': 'FALSE', 'light_cycle': 'Standard/default', 'local_lifespan_data': '', 'rack_setup': 'Ventilated', 'room_health_status': 'Other', 'room_temperature': '23', 'sex': 'M', 'strain': '


                                                                  ^
SyntaxError: EOL while scanning string literal
```

**Comment by maxsibilla** [comment]
`strain` had a strange character embedded that caused this function to fail. Manually updated the JSON for the affected sources
