### ISSUE TITLE
Error POSTing Samples and Datasets

### ISSUE THREAD

**Issue by shirey** [sennetconsortium/entity-api#6]
POST to `entity-api/entities/sample`
```
{ "sample_category":"block",  "lab_tissue_sample_id": "Bill-Test-777", "protocol_url": "https://dx.doi.org/10.17504/protocols.io.bf4cjqsw", "description": "testing sample", "group_uuid":"57192604-18e0-11ed-b79b-972795fc9504"}
```
or POST to `entity-api/entities/dataset`
```
{"data_types":["CODEX"], "group_uuid":"57192604-18e0-11ed-b79b-972795fc9504", "contains_human_genetic_sequences": false}
```

both result in:
```
[2022-08-28 20:58:41,848] ERROR in app: Exception on /entities/sample [POST]                                                                                
Traceback (most recent call last):                                                                                                                          
  File "/Users/bill/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 2073, in wsgi_app                                                       
    response = self.full_dispatch_request()                                                                                                                 
  File "/Users/bill/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1519, in full_dispatch_request                                          
    rv = self.handle_user_exception(e)                                                                                                                      
  File "/Users/bill/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1517, in full_dispatch_request                                          
    rv = self.dispatch_request()                                                                                                                            
  File "/Users/bill/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1503, in dispatch_request                                               
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                            
  File "/Users/bill/projects/sennet/entity-api/src/app.py", line 885, in create_entity                                                                      
    was_generated_by = json_data_dict['was_generated_by']                                                                                                   
KeyError: 'was_generated_by'                                                                                                            
```

**Comment by maxsibilla** [comment]
Updated Sample creation JSON:
`{
    "direct_ancestor_uuid": "0579c1d32ca1ecc698f9b7676af3b484",
    "sample_category": "block",
    "lab_tissue_sample_id": "Max-Test-777",
    "protocol_url": "https://dx.doi.org/10.17504/protocols.io.bf4cjqsw",
    "description": "testing sample"
}`

**Comment by maxsibilla** [comment]
Updated Dataset creation JSON:
`{
    "data_types": [
        "CODEX"
    ],
    "contains_human_genetic_sequences": false,
    "direct_ancestor_uuids": ["4e9829aa21ab57930440364830bbad12"]
}`
